name: Deploy to EC2

on:
  push:
    branches:
      - main  # Ganti jika kamu pakai branch lain

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout repositori
      - name: Checkout repository
        uses: actions/checkout@v2

      # Step 2: Setup SSH untuk koneksi ke EC2
      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}

      # Step 3: Install Node.js dan dependencies di EC2
      - name: Install Node.js and dependencies
        run: |
          ssh -o StrictHostKeyChecking=no ec2-user@${{ secrets.EC2_PUBLIC_IP }} << 'EOF'
            sudo apt update -y
            sudo apt install -y curl software-properties-common
            curl -fsSL https://deb.nodesource.com/setup_16.x | sudo -E bash -
            sudo apt install -y nodejs
            sudo apt install -y apache2
            cd ~/s3-uploader
            git pull origin main
            npm install
          EOF

      # Step 4: Export ENV variables dan jalankan aplikasi Node.js
      - name: Deploy app and set ENV
        run: |
          ssh -o StrictHostKeyChecking=no ec2-user@${{ secrets.EC2_PUBLIC_IP }} << EOF
            cd ~/s3-uploader
            git pull origin main
            npm install

            # Export ENV variables
            export AWS_ACCESS_KEY_ID="${{ secrets.AWS_ACCESS_KEY_ID }}"
            export AWS_SECRET_ACCESS_KEY="${{ secrets.AWS_SECRET_ACCESS_KEY }}"
            export AWS_REGION="${{ secrets.AWS_REGION }}"
            export S3_BUCKET_NAME="${{ secrets.S3_BUCKET_NAME }}"

            # Jalankan aplikasi Node.js di background
            nohup node app.js &
          EOF

      # Step 5: Restart Apache (karena kamu menggunakan Apache)
      - name: Restart Apache server
        run: |
          ssh -o StrictHostKeyChecking=no ec2-user@${{ secrets.EC2_PUBLIC_IP }} << 'EOF'
            sudo systemctl restart apache2
          EOF
