name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout repositori
      - name: Checkout repository
        uses: actions/checkout@v2

      # Step 2: Setup SSH untuk koneksi ke EC2
      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}

      # Step 3: Install Node.js di EC2
      - name: Install Node.js
        run: |
          ssh -o StrictHostKeyChecking=no ubuntu@${{ secrets.EC2_PUBLIC_IP }} << 'EOF'
            sudo apt update -y
            sudo apt install -y curl software-properties-common
            curl -fsSL https://deb.nodesource.com/setup_16.x | sudo -E bash -
            sudo apt install -y nodejs
          EOF

      # Step 4: Deploy app, set ENV, dan restart Node.js
      - name: Deploy app and restart Node.js
        run: |
          ssh -o StrictHostKeyChecking=no ubuntu@${{ secrets.EC2_PUBLIC_IP }} << EOF
            cd ~/s3-uploader
            git pull origin main
            npm install

            # Kill proses lama
            pkill -f "node app.js" || true

            # Export ENV dan jalankan ulang
            export AWS_ACCESS_KEY_ID="${{ secrets.AWS_ACCESS_KEY_ID }}"
            export AWS_SECRET_ACCESS_KEY="${{ secrets.AWS_SECRET_ACCESS_KEY }}"
            export AWS_REGION="${{ secrets.AWS_REGION }}"
            export S3_BUCKET_NAME="${{ secrets.S3_BUCKET_NAME }}"

            # Jalankan Node.js di background
            nohup node app.js > output.log 2>&1 &
          EOF

      # Step 5: Restart Apache server
      - name: Restart Apache server
        run: |
          ssh -o StrictHostKeyChecking=no ubuntu@${{ secrets.EC2_PUBLIC_IP }} << 'EOF'
            sudo systemctl restart apache2
          EOF
